/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.RunQuery;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASADULLAH
 */
public class CreateOrder extends javax.swing.JFrame {

    /**
     * Creates new form CreateOrder
     */
    public CreateOrder() {
        initComponents();
        try {
            String query = "Select * from Category;";
            ResultSet rs = RunQuery.getData(query);

            while (rs.next()) {
                int id = rs.getInt("CategoryID");
                String name = rs.getString("CatName");
                String Desc = rs.getString("CatDesc");
                String data[] = {Integer.toString(id), name, Desc};
                DefaultTableModel dt = (DefaultTableModel) cattable.getModel();
                dt.addRow(data);
            }
            try {
                String Query = "Select * from Product;";
                ResultSet rs1 = RunQuery.getData(Query);

                while (rs1.next()) {
                    int id = rs1.getInt("ItemID");
                    int categoryid = rs1.getInt("CategoryID");
                    String name = rs1.getString("Name");
                    int price = rs1.getInt("price");
                    String data[] = {Integer.toString(id), Integer.toString(categoryid), name, Integer.toString(price)};
                    DefaultTableModel dt = (DefaultTableModel) protable.getModel();
                    dt.addRow(data);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    String Id;

    CreateOrder(String userID) {
        Id = userID;
        initComponents();
        try {
            String query = "Select * from Category;";
            ResultSet rs = RunQuery.getData(query);

            while (rs.next()) {
                int id = rs.getInt("CategoryID");
                String name = rs.getString("CatName");
                String Desc = rs.getString("CatDesc");
                String data[] = {Integer.toString(id), name, Desc};
                DefaultTableModel dt = (DefaultTableModel) cattable.getModel();
                dt.addRow(data);
            }
            try {
                String Query = "Select * from Product;";
                ResultSet rs1 = RunQuery.getData(Query);

                while (rs1.next()) {
                    int id = rs1.getInt("ItemID");
                    int categoryid = rs1.getInt("CategoryID");
                    String name = rs1.getString("Name");
                    int price = rs1.getInt("price");
                    String data[] = {Integer.toString(id), Integer.toString(categoryid), name, Integer.toString(price)};
                    DefaultTableModel dt = (DefaultTableModel) protable.getModel();
                    dt.addRow(data);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cattable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        protable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        itemqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        itemid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cattable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cattable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 302, 142));

        protable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category ID", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        protable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(protable);
        protable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 302, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(3, 3, 3));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 118, -1));

        jLabel3.setBackground(new java.awt.Color(3, 3, 3));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Order Your Favourite Item");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 324, 64));

        jLabel4.setBackground(new java.awt.Color(3, 3, 3));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categories");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 118, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("Product ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, -1));

        itemqty.setBackground(new java.awt.Color(255, 255, 204));
        itemqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(itemqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 280, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 100, -1));

        price.setEditable(false);
        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, 32));

        itemid.setBackground(new java.awt.Color(255, 255, 204));
        itemid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemidActionPerformed(evt);
            }
        });
        getContentPane().add(itemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 280, 32));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Get Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, -1));

        back.setBackground(new java.awt.Color(102, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        back.setText("Dispatch Order");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 40));

        jButton3.setBackground(new java.awt.Color(102, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 110, 40));

        back1.setBackground(new java.awt.Color(102, 255, 255));
        back1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        back1.setText("See Your Orders");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        getContentPane().add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 200, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/images/kisspng-java-coffee-latte-tea-cafe-svg-icon-coffee-5ab0dbf7d8fef5.4718614115215400878888.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserAction u = new UserAction();
        if (!(itemid.getText().isEmpty() || itemqty.getText().isEmpty())) {
            int pr = u.CalculateBill(Integer.parseInt(itemid.getText()), Integer.parseInt(itemqty.getText()));
            if (pr == -1 || pr == 0) {
                JOptionPane.showMessageDialog(null, "Enter Product ID and Quantity and calculate price again.");
            } else {
                price.setText(Integer.toString(pr));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Product ID and Quantity.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        UserAction a = new UserAction();
        if (price.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Calculate Price by pushing button after Entering Values.");
        } else {
            if (itemqty.getText().equals("") || itemid.getText().equals("") ) {
                JOptionPane.showMessageDialog(null, "Enter Complete Details.");
            } else {
                if (price.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Caluclate price again with corect quantity and productid.");
                } else {
                    a.createOrder(Integer.parseInt(itemid.getText()), Integer.parseInt(itemqty.getText()), Integer.parseInt(price.getText()));

                    itemid.setText("");
                    itemqty.setText("");
                    price.setText("");
                }
            }
        }
    }//GEN-LAST:event_backActionPerformed

    private void itemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new CustomerHome(Id).setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        new MYOrders(Id).setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JTable cattable;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextField itemqty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField price;
    private javax.swing.JTable protable;
    // End of variables declaration//GEN-END:variables
}
