/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

/**
 *
 * @author ASADULLAH
 */
public class CustomerHome extends javax.swing.JFrame {

    public CustomerHome() {
        initComponents();
    }

    String id;

    CustomerHome(String a) {
        initComponents();
        id = a;
        System.out.print(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createAccBtn = new javax.swing.JButton();
        createAccBtn1 = new javax.swing.JButton();
        createAccBtn2 = new javax.swing.JButton();
        createAccBtn3 = new javax.swing.JButton();
        createAccBtn6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(3, 3, 3));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 99, 274, 64));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        createAccBtn.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn.setText("Create Orders");
        createAccBtn.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 239, 200, 39));

        createAccBtn1.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn1.setText("View Categories");
        createAccBtn1.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 349, 245, 39));

        createAccBtn2.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn2.setText("View Orders");
        createAccBtn2.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 349, 200, 39));

        createAccBtn3.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn3.setText("View All Products");
        createAccBtn3.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 239, 245, 39));

        createAccBtn6.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn6.setText("LOGOUT");
        createAccBtn6.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 200, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/images/kisspng-java-coffee-latte-tea-cafe-svg-icon-coffee-5ab0dbf7d8fef5.4718614115215400878888.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        this.setVisible(false);
        new CreateOrder(id).setVisible(true);
        // TODO add your handling code here:
        //        NewUser user = new NewUser();
        //        user.createacc(Name.getText(), Email.getText(), Phone.getText(), Address.getText(), Password.getText(), setSecurityQ.getText(), setAnswer.getText());
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void createAccBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtn1ActionPerformed
        this.setVisible(false);

        new ShowCategories().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_createAccBtn1ActionPerformed

    private void createAccBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtn2ActionPerformed
        this.setVisible(false);
        new MYOrders(id).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccBtn2ActionPerformed

    private void createAccBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtn3ActionPerformed
        this.setVisible(false);
        new ShowProducts(id).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_createAccBtn3ActionPerformed

    private void createAccBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtn6ActionPerformed
        this.setVisible(false);
        new CurrentUser();
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccBtn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccBtn;
    private javax.swing.JButton createAccBtn1;
    private javax.swing.JButton createAccBtn2;
    private javax.swing.JButton createAccBtn3;
    private javax.swing.JButton createAccBtn6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
