/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

/**
 *
 * @author ASADULLAH
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        createAccBtn = new javax.swing.JButton();
        loginNavBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        setAnswer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        setSecurityQ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 15, 196, 56));

        jLabel2.setBackground(new java.awt.Color(242, 200, 242));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 77, 86, -1));

        Name.setBackground(new java.awt.Color(255, 255, 230));
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 80, 176, 25));

        jLabel3.setBackground(new java.awt.Color(242, 200, 242));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 123, 86, -1));

        Email.setBackground(new java.awt.Color(255, 255, 230));
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 126, 176, 25));

        jLabel4.setBackground(new java.awt.Color(242, 200, 242));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phone No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 169, 86, -1));

        Phone.setBackground(new java.awt.Color(255, 255, 230));
        Phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 172, 176, 25));

        jLabel5.setBackground(new java.awt.Color(242, 200, 242));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 215, 86, -1));

        Address.setBackground(new java.awt.Color(255, 255, 230));
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 218, 176, 25));

        jLabel6.setBackground(new java.awt.Color(242, 200, 242));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 261, 86, -1));

        Password.setBackground(new java.awt.Color(255, 255, 230));
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 264, 176, 25));

        createAccBtn.setBackground(new java.awt.Color(51, 255, 204));
        createAccBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        createAccBtn.setText("Create Account");
        createAccBtn.setBorder(new javax.swing.border.MatteBorder(null));
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 393, 151, 39));

        loginNavBtn.setBackground(new java.awt.Color(51, 255, 204));
        loginNavBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        loginNavBtn.setText("LOGIN");
        loginNavBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginNavBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNavBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginNavBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 456, 70, -1));

        jLabel7.setBackground(new java.awt.Color(242, 200, 242));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 353, 86, -1));

        setAnswer.setBackground(new java.awt.Color(255, 255, 230));
        setAnswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(setAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 356, 176, 25));

        jLabel9.setBackground(new java.awt.Color(242, 200, 242));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Security Question");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 307, 151, -1));

        setSecurityQ.setBackground(new java.awt.Color(255, 255, 230));
        setSecurityQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setSecurityQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSecurityQActionPerformed(evt);
            }
        });
        getContentPane().add(setSecurityQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 310, 176, 25));

        jLabel8.setBackground(new java.awt.Color(84, 255, 232));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/logo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/management/system/images/coffee-logo-design-creative-idea-logo-elements-2.png"))); // NOI18N
        jLabel10.setFocusTraversalPolicyProvider(true);
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setIconTextGap(1);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-480, -120, 1540, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginNavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNavBtnActionPerformed
        new LOGIN().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_loginNavBtnActionPerformed

    public void clear() {
        Name.setText("");
        Email.setText("");
        Phone.setText("");
        Address.setText("");
        Password.setText("");
        setSecurityQ.setText("");
        setAnswer.setText("");
    }
    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        // TODO add your handling code here:
        NewUser user = new NewUser();
        int a = user.createacc(Name.getText(), Email.getText(), Phone.getText(), Address.getText(), Password.getText(), setSecurityQ.getText(), setAnswer.getText());
        if (a == 0) {
        } else {
            clear();
        }
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void setSecurityQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSecurityQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setSecurityQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
        new Signup().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginNavBtn;
    private javax.swing.JTextField setAnswer;
    private javax.swing.JTextField setSecurityQ;
    // End of variables declaration//GEN-END:variables
}
